name: GitHub Profile Views Counter CI
on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  release:
    name: GitHub Profile Views Counter Action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
          
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.0
          
      - name: Agreegate github insights data
        uses: gayanvoice/github-profile-views-counter-action@3.0.0
        env:
          INSIGHTS_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
