name: GitHub Profile Views Counter CI
on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  release:
    name: GitHub Profile Views Counter Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.SNIGDHASJG_GITHUB_APP_ID }}
          private-key: ${{ secrets.SNIGDHASJG_GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.0

      - name: Agreegate github insights data
        uses: gayanvoice/github-profile-views-counter-action@3.0.0
        env:
          INSIGHTS_TOKEN: ${{ steps.app-token.outputs.token }}
